Adds code coverage recommendations in GitHub workflow. (#4489)
* Prepares Github workflow for future code coverage requirements.

* Omits coverage for specified files. Adds coverage details to log message.

* Fixes GitHub workflow variable references.

* Moves variable assignment to appropriate scope.

* Fixes code coverage check per file.

* Ignores code coverage for specified files.

* Adds percentage symbol to code coverage message.

* Improves text alignment for code coverage log messages.

* Improves text alignment for code coverage log messages.

* Improves text alignment for code coverage log messages.

* Fixes formatting.

* Fixes formatting.

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -4,6 +4,11 @@ on: pull_request
 
 jobs:
   test:
+    env:
+      # Minimum code coverage per file
+      COVERAGE_SINGLE: 50
+      # Minimum total code coverage
+      COVERAGE_TOTAL: 70
     runs-on: ubuntu-latest
     services:
       postgres:
@@ -41,4 +46,21 @@ jobs:
       - name: Test with pytest
         run: |
           pip install pytest-cov
-          pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
+          pytest --junitxml=junit/test-results.xml --cov=dispatch --cov-report=json:coverage.json --cov-report=xml --cov-report=html
+      - name: Coverage per file
+        # TODO: Change this recommendation into a requirement.
+        run: |
+          export FAILED_COVERAGE_PER_FILE=$(python -c "import json;files=json.load(open('coverage.json'))['files'];covs=map(lambda k, v: (k, v['summary']['percent_covered_display']),files.keys(),files.values()); f=filter(lambda cov:int(cov[1])<${{ env.COVERAGE_SINGLE }},covs); print('\n'.join('{:<68}{:>3}%'.format(k,v) for k,v in f))")
+          if [[ $FAILED_COVERAGE_PER_FILE != "" ]]; then
+            echo "FAIL Recommended file(s) test coverage of ${{ env.COVERAGE_SINGLE }}% not reached."
+            echo -e "Failed file coverage(s):\n$FAILED_COVERAGE_PER_FILE"
+            # exit 1
+          fi
+      - name: Coverage total
+        # TODO: Change this recommendation into a requirement.
+        run: |
+          export COVERAGE_TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
+          if [[ $COVERAGE_TOTAL < ${{ env.COVERAGE_TOTAL }} ]]; then
+            echo "FAIL Recommended total test coverage of ${{ env.COVERAGE_TOTAL }}% not reached. Total coverage: $COVERAGE_TOTAL%"
+            # exit 1
+          fi
